#! /bin/bash
# this script de-interleaves a fasta file, AND sorts it by name
# args: deinterleave_sort_fasta <[input] >[output]

sed -r 's/(>.*)/%\1@/' <$1 | tr -d '\n' | tr '%' '\n' | sort | tr '@' '\n' | sed 1d 
