#! /bin/bash
# this script de-interleaves a fasta file, but does NOT sort it. 
# args: deinterleave_fasta <[input] >[output]
sed -r 's/(>.*)/%\1@/' <$1 | tr -d '\n' | tr '%' '\n' | tr '@' '\n' | sed 1d 

