#! /bin/bash
# this script de-interleaves a fasta file, AND sorts it by LENGTH
# args: deinterleave_sort_fasta_length <[input] >[output]

sed -r 's/(>.*)/%\1@/' <$1 | tr -d '\n' | tr '%' '\n' | tr '@' '\n' | sed 1d | perl -e 'while (<>) {$h=$_; $s=<>; $seqs{$h}=$s;} foreach $header (reverse sort {length($seqs{$a}) <=> length($seqs{$b})} keys %seqs) {print $header.$seqs{$header}}'
